### ISSUE TITLE
error when using setBackground command

### ISSUE THREAD

**Issue by Ahlam-dev** [usecallmanagernz/commands#1]
`Hi there,
I found your website while searching for a way to set the background of cisco IP Phone Model 8865 and I followed your code 
but using nodejs to send the http post request .
```
url : http://phoneIP/CGI/Execute
auth: using basic auth
body : {"XML": "<?xml version="1.0" encoding="UTF-8"?><setBackground><background><image>http://myimg.png</image><icon>http://myicon.png</icon></background></setBackground>"}
```

but I'm getting this response :
**Unsupported Operation Device doesn't support this operation**

I checked my IP phone console log and found these results 

```
4357 INF Oct 12 14:57:51.587391 (17139-17290) JAVA-HTTP JNI| Curl_ssl_secd_connect: return from secSSLConnect, rc=0
4358 INF Oct 12 14:57:51.587407 (17139-17290) JAVA-HTTP JNI| Curl_ssl_secd_connect: exit
4359 INF Oct 12 14:57:51.587422 (17139-17290) JAVA-HTTP JNI| Curl_setup_conn: return from Curl_protocol_connect, result=0
4360 INF Oct 12 14:57:51.587440 (17139-17290) JAVA-HTTP JNI| Curl_do_perform: connect_host res=0
4361 INF Oct 12 14:57:51.587537 (17139-17290) JAVA-HTTP JNI| Curl_add_buffer_send: enter
4362 INF Oct 12 14:57:51.587560 (17139-17290) JAVA-HTTP JNI| Curl_write: num=0
4363 INF Oct 12 14:57:51.587578 (17139-17290) JAVA-HTTP JNI| secd_send: enter
4364 INF Oct 12 14:57:51.587748 (17139-17290) JAVA-HTTP JNI| secd_send: result=397
4365 INF Oct 12 14:57:51.587772 (17139-17290) JAVA-HTTP JNI| Curl_write: bytes_written=397
4366 INF Oct 12 14:57:51.587797 (17139-17290) JAVA-HTTP JNI| Curl_do_perform: return from Curl_do, result=0
4367 INF Oct 12 14:57:51.587815 (17139-17290) JAVA-HTTP JNI| Transfer: enter
4368 INF Oct 12 14:57:51.587831 (17139-17290) JAVA-HTTP JNI| Transfer: readsockfd=103
4369 DEB Oct 12 14:57:51.587846 (17139-17290) JAVA-HTTP JNI| Transfer: let SSL to read socket
4370 INF Oct 12 14:57:51.587862 (17139-17290) JAVA-HTTP JNI| secd_recv: enter
4371 ERR Oct 12 14:57:51.587921 (17139-17290) JAVA-SSL_READ error 2
4372 ERR Oct 12 14:57:51.688050 (17139-17290) JAVA-SSL_READ error 2
4373 ERR Oct 12 14:57:51.788189 (17139-17290) JAVA-SSL_READ error 2
4374 INF Oct 12 14:57:51.888429 (17139-17290) JAVA-HTTP JNI| secd_recv: result=535
4375 INF Oct 12 14:57:51.888654 (17139-17290) JAVA-HTTP JNI| Curl_do_perform: return from Transfer, result=0
4376 DEB Oct 12 14:57:51.888727 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4377 DEB Oct 12 14:57:51.888763 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4378 DEB Oct 12 14:57:51.888794 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4379 DEB Oct 12 14:57:51.888822 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4380 DEB Oct 12 14:57:51.888845 (17139-17290) JAVA-SSL shutdown.
4381 DEB Oct 12 14:57:51.888961 (17139-17290) JAVA-BIO reset.
4382 DEB Oct 12 14:57:51.888983 (17139-17290) JAVA-SSL free.
4383 DEB Oct 12 14:57:51.889141 (17139-17290) JAVA-Closing socket.
4384 DEB Oct 12 14:57:51.889241 (17139-17290) JAVA-Sec SSL Connection  - Deleted SSL connection handle 0x40f559c8, connDesc 103 from table.
4385 NOT Oct 12 14:57:51.889264 (17139-17290) JAVA-Close and free connection handler at 0x40f559c8
4386 NOT Oct 12 14:57:51.889283 (17139-17290) JAVA-Sec SSL Close Connection successful.
4387 DEB Oct 12 14:57:51.889316 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4388 DEB Oct 12 14:57:51.889346 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4389 DEB Oct 12 14:57:51.889374 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4390 DEB Oct 12 14:57:51.889402 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4391 DEB Oct 12 14:57:51.889431 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4392 DEB Oct 12 14:57:51.889460 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4393 DEB Oct 12 14:57:51.889489 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4394 DEB Oct 12 14:57:51.889516 (17139-17290) JAVA-[getDeployMode] deploy-mode:1 
4395 NOT Oct 12 14:57:51.889547 (17139-17290) JAVA-HTTP JNI| processHttpRequest: return from http response, [res] = 0
4396 ERR Oct 12 14:57:51.889956 (17139-17290) JAVA-HTTP JNI| processHttpRequest: error process connection 1
4397 NOT Oct 12 14:57:51.890412 (17139-17380) JAVA-HTTP JNI| httpServerHandler: uri=/CGI/Execute
4398 NOT Oct 12 14:57:51.891281 (17139-17380) JAVA-Thread-20|cip.xml.XmlParser:parse - Encoding Updated to UTF-8
4399 ERR Oct 12 14:57:51.892957 (17139-17345) JAVA- - The phone could not access the wallpaper list and the wallpaper could not be changed
4400 INF Oct 12 14:57:51.893025 (17139-17304) JAVA- - The phone could not access the wallpaper list and the wallpaper could not be changedPushThread|cip.push.PushThread:execute - Sleep for 100ms previous= current=Display:On:60 i=0 total=1
4401 WRN Oct 12 14:57:51.893056 (17139-17345) JAVA-Cisco/UserPrefs MQThread|PersonalizationHandler:msui.PersonalizationError - type=Unsupported Operationdate=Device doesn't support this operationhttp.error.code=400
4402 NOT Oct 12 14:57:51.893364 (17139-17286) JAVA-HTTP JNI| Java_cip_http_NativeHttpTask_updateCgiRequest: conId=0, state=3, error=400
4403 NOT Oct 12 14:57:51.893528 (17139-17380) JAVA-HTTP JNI| httpServerHandler: pushStatus=3, pushError=400
4404 NOT Oct 12 14:57:51.893657 (17139-17380) JAVA-HTTP JNI| processStatusResponse: call mg_printf with HTTP/1.1 400 Bad Request Content-Type: text/xml Content-Length: 167 Content: <?xml version="1.0" encoding="utf-8"?>^M
	<errorResponse>^M
	<type> Unsupported Operation</type> ^M
	<data> Device doesn't support this operation</data> ^M
	</errorResponse>^M
```

Thanks in advance

**Comment by gareth-palmer** [comment]
Do you get the same result using `setbackground` script in this repository?

`<phonePersonalization>` needs to be enabled in SEPMAC.cnf.xml: https://usecallmanager.nz/sepmac-cnf-xml.html#phonePersonalization

**Comment by Ahlam-dev** [comment]
<phonePersonalization> is enabled but now I'm getting another response message :  **InvalidURLdate Http Failed** 
when I checked the console log .. it seems to accept backgound image URL then it gives me some errors before accepting Icon image.. I  tried your script as well and I'm getting the same results.
below are my console logs.
`
5634 NOT Oct 13 13:05:30.636758 (6985-7127) JAVA-HTTP JNI| processHttpRequest: return from http response, [res] = 0
5635 NOT Oct 13 13:05:30.636805 (6985-7127) JAVA-HTTP JNI| processHttpResponseFromJava: req_id=12, status=3, response code=301
5636 NOT Oct 13 13:05:30.636828 (6985-7127) JAVA-HTTP JNI| processHttpResponseFromJava: content-length=0, content-type=0, charset=, www-authenticate=,             location: https://upload.wikimedia.org/wikipedia/commons/f/ff/800x480-Y_Ddraig_Goch.png, refresh: 0, refreshPath: , date: 1665655507, expires: 0, response file: http_resp_12_113.x
5637 NOT Oct 13 13:05:30.636850 (6985-7127) JAVA-HTTP JNI| processHttpResponseFromJava: relocation happens, req_id=12
5638 INF Oct 13 13:05:30.637012 (6985-7127) JAVA-HttpClientWorkingThread|cip.http.HttpClientConnection:? - response status: 3, response code: 301
5639 WRN Oct 13 13:05:30.637068 (6985-7127) JAVA-HttpClientWorkingThread|cip.http.HttpClientConnection:registerRequest - Current State = 2
5640 NOT Oct 13 13:05:30.637519 (6985-7127) JAVA-HTTP JNI| processHttpResponseFromJava: complete sending response to Java
5641 NOT Oct 13 13:05:30.637582 (6985-7127) JAVA-HTTP JNI| processHttpRequest: complete processing connection 12
5642 NOT Oct 13 13:05:30.637743 (6985-24193) JAVA-DNS LOOKUP |NetUtil:? - [getIPAddress] ipmode: IPv4 Only, ipv4-stack-state: DHCP BOUND(valid:true), ipv6-stack-state: IPV6 STACK TURNED OFF(valid:false)
5643 INF Oct 13 13:05:30.638286 dnsmasq[6941]: query[A] upload.wikimedia.org from 127.0.0.1
5644 INF Oct 13 13:05:30.638336 dnsmasq[6941]: cached upload.wikimedia.org is 91.198.174.208
5645 NOT Oct 13 13:05:30.638496 (6985-24193) JAVA-DNS LOOKUP |NetUtil:? - [getIPAddress] ip[0]=91.198.174.208
5646 WRN Oct 13 13:05:30.638706 (6985-24193) JAVA-DNS LOOKUP |cip.http.HttpClientConnection:registerRequest - Current State = 5
5647 ERR Oct 13 13:05:30.639353 (6985-7125) JAVA-HTTP JNI| deleteFile: failed to delete file! fileName=, errno=2
5648 NOT Oct 13 13:05:30.639524 (6985-7128) JAVA-HTTP JNI| processHttpRequest: start processing connection 13
5649 DEB Oct 13 13:05:30.639606 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5650 DEB Oct 13 13:05:30.639641 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5651 DEB Oct 13 13:05:30.639670 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5652 NOT Oct 13 13:05:30.639758 (6985-7128) JAVA-HTTP JNI| buildHttpReqHeader: adding cookie header, COOKIE:
5653 NOT Oct 13 13:05:30.639784 (6985-7128) JAVA-HTTP JNI| buildHttpReqHeader: adding customer header, x-CiscoIPPhoneModelName: CP-8865
5654 NOT Oct 13 13:05:30.639805 (6985-7128) JAVA-HTTP JNI| buildHttpReqHeader: adding customer header, x-CiscoIPPhoneSDKVersion: 8.5.1
5655 NOT Oct 13 13:05:30.639824 (6985-7128) JAVA-HTTP JNI| buildHttpReqHeader: adding customer header, x-CiscoIPPhoneDisplay: 498,289,24,C
5656 NOT Oct 13 13:05:30.640131 (6985-7128) JAVA-HTTP JNI| processHttpRequest: sending http request out...
5657 INF Oct 13 13:05:30.640168 (6985-7128) JAVA-HTTP JNI| Curl_do_perform: enter
5658 INF Oct 13 13:05:30.640195 (6985-7128) JAVA-HTTP JNI| connect_host: enter
5659 INF Oct 13 13:05:30.640213 (6985-7128) JAVA-HTTP JNI| Curl_connect: enter
5660 INF Oct 13 13:05:30.640252 (6985-7128) JAVA-HTTP JNI| parseurlandfillconn: hit6, protop:https
5661 INF Oct 13 13:05:30.640786 dnsmasq[6941]: query[A] upload.wikimedia.org from 127.0.0.1
5662 INF Oct 13 13:05:30.640812 dnsmasq[6941]: cached upload.wikimedia.org is 91.198.174.208
5663 INF Oct 13 13:05:30.640920 (6985-7128) JAVA-HTTP JNI| Curl_setup_conn: enter
5664 INF Oct 13 13:05:30.640966 (6985-7128) JAVA-HTTP JNI| singleipconnect: enter
5665 NOT Oct 13 13:05:30.641013 (6985-7128) JAVA-HTTP JNI| sockoptCallback: succesfully setsockopt IP_TOS=0
5666 INF Oct 13 13:05:30.641034 (6985-7128) JAVA-HTTP JNI| singleipconnect: go ahead with the bind/connect
5667 INF Oct 13 13:05:30.737585 (6985-7128) JAVA-HTTP JNI| Curl_connecthost: return from singleipconnect, result=0
5668 INF Oct 13 13:05:30.737628 (6985-7128) JAVA-HTTP JNI| ConnectPlease: return from Curl_connecthost, result=0
5669 INF Oct 13 13:05:30.737651 (6985-7128) JAVA-HTTP JNI| Curl_setup_conn: return from ConnectPlease, result=0
5670 INF Oct 13 13:05:30.737672 (6985-7128) JAVA-HTTP JNI| Curl_http_connect: enter
5671 DEB Oct 13 13:05:30.737718 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5672 DEB Oct 13 13:05:30.737753 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5673 DEB Oct 13 13:05:30.737782 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5674 DEB Oct 13 13:05:30.737810 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5675 INF Oct 13 13:05:30.737830 (6985-7128) JAVA-HTTP JNI| Curl_ssl_secd_connect: enter
5676 ERR Oct 13 13:05:30.737850 (6985-7128) JAVA-Sec SSL initialization - duplicate initialization request
5677 INF Oct 13 13:05:30.737867 (6985-7128) JAVA-HTTP JNI| Curl_ssl_secd_connect: initializing default SSL context
5678 INF Oct 13 13:05:30.837972 (6985-7128) JAVA-HTTP JNI| Curl_ssl_secd_connect: ip=91.198.174.208, port=443
5679 INF Oct 13 13:05:30.838043 (6985-7128) JAVA-HTTP JNI| Curl_ssl_secd_connect: before secBIOSSLConnect
5680 INF Oct 13 13:05:30.888346 (6985-7128) JAVA-Sec SSL Connection - HTTPS_TLS.
5681 INF Oct 13 13:05:30.888388 (6985-7128) JAVA-Sec SSL Connection - ciphers:[ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA]
5682 DEB Oct 13 13:05:30.888409 (6985-7128) JAVA-sec_filter_out_ciphers: cipher lister is:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA
5683 ERR Oct 13 13:05:30.888650 (366-24196) SECUREAPP-filterOutCiphers:0 ret:1
5684 ERR Oct 13 13:05:30.938611 (6985-7128) JAVA-ret from recvSecRep,ret 0
5685 ERR Oct 13 13:05:30.938647 (6985-7128) JAVA-cipherList is: 0
5686 DEB Oct 13 13:05:30.938713 (6985-7128) JAVA-sec_filter_out_ciphers: filter out cipher lister is:0
5687 DEB Oct 13 13:05:30.938734 (6985-7128) JAVA-sec_parse_cipher_from_list: cipherList:0
5688 DEB Oct 13 13:05:30.938754 (6985-7128) JAVA-sec_parse_cipher_from_list: cipherList is only one item value is :0 
5689 DEB Oct 13 13:05:30.938770 (6985-7128) JAVA-sec_filter_out_ciphers: list has 1 items 
5690 DEB Oct 13 13:05:30.938788 (6985-7128) JAVA-sec_filter_out_ciphers: cipher list is:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA
5691 DEB Oct 13 13:05:30.938805 (6985-7128) JAVA-sec_filter_out_ciphers: number cipher is :0 
5692 DEB Oct 13 13:05:30.938822 (6985-7128) JAVA-sec_filter_out_ciphers: cipher is :[] 
5693 DEB Oct 13 13:05:30.938839 (6985-7128) JAVA-sec_filter_out_ciphers: now cipherList is - [ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA] 
5694 INF Oct 13 13:05:30.939112 (6985-7128) JAVA-SSL session setup - Requesting Cert
5695 INF Oct 13 13:05:30.939133 (6985-7128) JAVA-HTTP JNI| getActiveCertificateData: Invoking sec_get_activeCert API
5696 DEB Oct 13 13:05:30.939204 (6985-7128) JAVA-** Enter Into : sec_get_cert
5697 DEB Oct 13 13:05:30.939224 (6985-7128) JAVA-MIC Cert get sec_get_cert:
5698 INF Oct 13 13:05:30.989419 (6985-7128) JAVA-[truncated] HTTP JNI| getActiveCertificateData: 
5699 INF Oct 13 13:05:30.989474 (6985-7128) JAVA-SSL session setup - Get Active cert ok
5700 DEB Oct 13 13:05:30.989496 (6985-7128) JAVA-SSL session setup - cert len=1159, type=MIC
5701 DEB Oct 13 13:05:30.989799 (6985-7128) JAVA-Certificate subject name = /serialNumber=PID:CP-8865 SN:PUC202407CT/O=Cisco Systems Inc./OU=CTG/CN=CP-8865-SEP00CCFC99A107
5702 DEB Oct 13 13:05:30.989833 (6985-7128) JAVA-SSL session setup - Certificate issuer name = /O=Cisco/CN=Cisco Manufacturing CA SHA2
5703 INF Oct 13 13:05:30.989918 (6985-7128) JAVA-Returning RSA sec SSL private encrypt/decrypt method
5704 DEB Oct 13 13:05:30.989940 (6985-7128) JAVA-SSL session setup - changed default RSA method.
5705 INF Oct 13 13:05:30.989963 (6985-7128) JAVA-Setup SSL session - SSL use certificate okay
5706 INF Oct 13 13:05:30.989998 (6985-7128) JAVA-Setup SSL session - SSL use private key okay
5707 DEB Oct 13 13:05:30.990247 (6985-7128) JAVA-Sec SSL Connection  - Added SSL connection handle 0x1e2fb30, connDesc 104 to table.
5708 DEB Oct 13 13:05:30.990272 (6985-7128) JAVA-Sec SSL Connection - check status & perform handshake.
5709 DEB Oct 13 13:05:30.990514 (6985-7128) JAVA-Sec SSL Connection - handshake done or in progress.
5710 INF Oct 13 13:05:30.990540 (6985-7128) JAVA-HTTP JNI| Curl_ssl_secd_connect: after secBIOSSLConnect, handle=31652656
5711 DEB Oct 13 13:05:30.990562 (6985-7128) JAVA-Sec SSL Connection - check status & perform handshake.
5712 DEB Oct 13 13:05:31.090694 (6985-7128) JAVA-Sec SSL Connection - check status & perform handshake.
5713 ERR Oct 13 13:05:31.090796 (6985-7128) JAVA-Sec SSL Connection - Handshake failed.
5714 INF Oct 13 13:05:31.090820 (6985-7128) JAVA-HTTP JNI| Curl_ssl_secd_connect: return from secSSLConnect, rc=-2
5715 INF Oct 13 13:05:31.090838 (6985-7128) JAVA-HTTP JNI| Curl_ssl_secd_connect: exit
5716 DEB Oct 13 13:05:31.090856 (6985-7128) JAVA-SSL shutdown.
5717 DEB Oct 13 13:05:31.090877 (6985-7128) JAVA-BIO reset.
5718 DEB Oct 13 13:05:31.090893 (6985-7128) JAVA-SSL free.
5719 DEB Oct 13 13:05:31.091063 (6985-7128) JAVA-Closing socket.
5720 DEB Oct 13 13:05:31.091159 (6985-7128) JAVA-Sec SSL Connection  - Deleted SSL connection handle 0x1e2fb30, connDesc 104 from table.
5721 NOT Oct 13 13:05:31.091184 (6985-7128) JAVA-Close and free connection handler at 0x1e2fb30
5722 NOT Oct 13 13:05:31.091201 (6985-7128) JAVA-Sec SSL Close Connection successful.
5723 INF Oct 13 13:05:31.091218 (6985-7128) JAVA-HTTP JNI| Curl_setup_conn: return from Curl_protocol_connect, result=35
5724 DEB Oct 13 13:05:31.091274 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5725 DEB Oct 13 13:05:31.091307 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5726 DEB Oct 13 13:05:31.091337 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5727 DEB Oct 13 13:05:31.091367 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5728 DEB Oct 13 13:05:31.091397 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5729 DEB Oct 13 13:05:31.091427 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5730 DEB Oct 13 13:05:31.091456 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5731 DEB Oct 13 13:05:31.091483 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5732 DEB Oct 13 13:05:31.091511 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5733 DEB Oct 13 13:05:31.091538 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5734 DEB Oct 13 13:05:31.091567 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5735 DEB Oct 13 13:05:31.091596 (6985-7128) JAVA-[getDeployMode] deploy-mode:1 
5736 INF Oct 13 13:05:31.091634 (6985-7128) JAVA-HTTP JNI| Curl_do_perform: connect_host res=35
5737 NOT Oct 13 13:05:31.091661 (6985-7128) JAVA-HTTP JNI| processHttpRequest: return from http response, [res] = 35
5738 ERR Oct 13 13:05:31.091679 (6985-7128) JAVA-HTTP JNI| processHttpRequest: request aborted, [res] = 35
5739 NOT Oct 13 13:05:31.091726 (6985-7128) JAVA-HTTP JNI| processHttpResponseFromJava: req_id=13, status=19, response code=0
5740 NOT Oct 13 13:05:31.091748 (6985-7128) JAVA-HTTP JNI| processHttpResponseFromJava: content-length=0, content-type=0, charset=, www-authenticate=,             location: , refresh: 0, refreshPath: , date: 0, expires: 0, response file: http_resp_13_114.x
5741 INF Oct 13 13:05:31.091918 (6985-7128) JAVA-HttpClientWorkingThread|cip.http.HttpClientConnection:? - response status: 19, response code: 0
5742 WRN Oct 13 13:05:31.091976 (6985-7128) JAVA-HttpClientWorkingThread|cip.http.HttpClientConnection:? - listener.httpFailed
5743 NOT Oct 13 13:05:31.092044 (6985-7128) JAVA-HTTP JNI| processHttpResponseFromJava: complete sending response to Java
5744 NOT Oct 13 13:05:31.092092 (6985-7128) JAVA-HTTP JNI| processHttpRequest: complete processing connection 13
5745 WRN Oct 13 13:05:31.092775 (6985-7185) JAVA-Cisco/UserPrefs MQThread|PersonalizationHandler:msui.PersonalizationError - type=InvalidURLdate= Http Failed http.error.code=19`

**Comment by gareth-palmer** [comment]
The phone can't use HTTPS until either the certificate being used by the web-server is in ITLFile.tlv or there is a TVS service to validate it. Use HTTP instead.
